import type { Impact, Violation } from "@/lib/a11y"

/**
 * Draft Accessibility Conformance Report (ACR / VPAT-style) from an axe scan.
 * This is an automated draft — not a signed legal attestation.
 */

export type StatementInput = {
  host: string
  url: string
  scannedAt: string
  score: number
  standards: string[]
  rulesPassed: number | null
  violationsCount: number
  counts: Record<Impact, number>
  violations: Violation[]
  productName?: string
}

export function buildConformanceStatementHtml(input: StatementInput): string {
  const product = input.productName || input.host
  const date = new Date(input.scannedAt).toISOString().slice(0, 10)
  const rows = input.violations
    .map(
      (v) =>
        `<tr>
          <td>${escapeHtml(v.id)}</td>
          <td>${escapeHtml(v.impact)}</td>
          <td>${escapeHtml(v.help)}</td>
          <td>${v.nodes.length}</td>
          <td>Does Not Support (automated)</td>
        </tr>`
    )
    .join("\n")

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Accessibility Conformance Statement — ${escapeHtml(product)}</title>
  <style>
    body { font-family: Georgia, "Times New Roman", serif; color: #0f172a; max-width: 48rem; margin: 2rem auto; padding: 0 1.25rem; line-height: 1.55; }
    h1, h2 { font-family: system-ui, sans-serif; letter-spacing: -0.02em; }
    h1 { font-size: 1.75rem; }
    h2 { font-size: 1.15rem; margin-top: 2rem; }
    .meta { color: #475569; font-size: 0.95rem; }
    .banner { border: 1px solid #f59e0b; background: #fffbeb; padding: 0.75rem 1rem; border-radius: 0.5rem; font-size: 0.9rem; }
    table { width: 100%; border-collapse: collapse; font-size: 0.85rem; margin-top: 0.75rem; }
    th, td { border: 1px solid #cbd5e1; padding: 0.4rem 0.5rem; text-align: left; vertical-align: top; }
    th { background: #f8fafc; font-family: system-ui, sans-serif; }
    @media print { body { margin: 0; } .no-print { display: none; } }
  </style>
</head>
<body>
  <p class="no-print meta"><button onclick="window.print()">Print / Save as PDF</button></p>
  <h1>Accessibility Conformance Statement</h1>
  <p class="meta">Draft ACR generated by A11yFix · ${escapeHtml(date)}</p>

  <div class="banner">
    <strong>Important:</strong> This document is an <em>automated draft</em> based on
    axe-core WCAG rule tags (${escapeHtml(input.standards.join(", "))}).
    It is <strong>not</strong> a complete VPAT®, a formal Accessibility Conformance Report
    signed by a qualified auditor, or legal advice. Manual testing and human review remain required.
  </div>

  <h2>1. Product</h2>
  <p><strong>Name:</strong> ${escapeHtml(product)}<br/>
  <strong>Product description:</strong> Web property at ${escapeHtml(input.host)}<br/>
  <strong>Product version / URL evaluated:</strong> ${escapeHtml(input.url)}<br/>
  <strong>Report date:</strong> ${escapeHtml(date)}</p>

  <h2>2. Contact</h2>
  <p>For accessibility inquiries related to this draft, contact the website owner.
  Tooling support: <a href="mailto:support@geta11yfix.com">support@geta11yfix.com</a>.</p>

  <h2>3. Evaluation methods</h2>
  <p>Automated evaluation with axe-core against WCAG 2.x Level A and AA rule tags.
  Score model: A11yFix composite score <strong>${input.score} / 100</strong>
  (${input.violationsCount} violated rules;
  critical ${input.counts.critical}, serious ${input.counts.serious},
  moderate ${input.counts.moderate}, minor ${input.counts.minor}
  ${input.rulesPassed != null ? `; rules passed ${input.rulesPassed}` : ""}).</p>

  <h2>4. Applicable standards / guidelines</h2>
  <ul>
    <li>Web Content Accessibility Guidelines (WCAG) 2.0 / 2.1 / 2.2 Level A and AA (automated subset)</li>
  </ul>

  <h2>5. Conformance summary (automated)</h2>
  <p>Where no automated violations were reported for a success criterion covered by axe,
  status is listed as <strong>Supports (automated only)</strong>. Criteria with findings
  below are <strong>Does Not Support (automated)</strong>. Criteria not covered by axe
  are <strong>Not Evaluated</strong> and must be assessed manually.</p>

  <h2>6. Findings requiring remediation</h2>
  ${
    input.violations.length === 0
      ? "<p>No axe-core WCAG A/AA violations were reported on this URL at evaluation time.</p>"
      : `<table>
    <thead>
      <tr><th>Rule ID</th><th>Impact</th><th>Description</th><th>Nodes</th><th>Status</th></tr>
    </thead>
    <tbody>
      ${rows}
    </tbody>
  </table>`
  }

  <h2>7. Legal disclaimer</h2>
  <p>A11yFix provides tooling to help teams find and fix accessibility issues.
  Use of this draft statement does not guarantee compliance with the ADA, Section 508,
  the European Accessibility Act, or any other law. Procurement teams should request a
  full VPAT/ACR prepared under their required edition (e.g. WCAG 2.1 or 2.2) with manual testing.</p>

  <p class="meta">Generated by <a href="https://www.geta11yfix.com">A11yFix</a>.</p>
</body>
</html>`
}

function escapeHtml(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
}
